sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
matrix:
   fast_finish: true
   allow_failures:
     - node_js: '0.10'
     - node_js: '0.12'
