name: CI

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [22.x]
        platform:
        # - os: ubuntu-latest
        #   shell: bash
        # - os: macos-latest
        #   shell: bash
        - os: windows-latest
          shell: bash
        # - os: windows-latest
        #   shell: powershell
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
      - run: npm test -- test/integration/eperm.ts --disable-coverage --grep=. --grep=async
